AllCops:
  Exclude:
    - 'test_script.rb'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
    - 'test/**/*'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Style/GuardClause:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
