# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ea8ab6a99e48df236f760fbbbbc88dd8e84c185086ae7574f8a403685b0901f790afa661bd381144c4f872ccde9e7c040bfab79d13b8fcf2c4a740f043fcea3

test:
  secret_key_base: 4cef52a581200c5f68d46c858eb9ec4c026428f0dc509343e2ad7324306387c64905d97e5a7741fc56901b9eed0ed749c298fc72a4864e26005ab6d8f801a27b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
